/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author Sooo SE
 */
public class Main extends javax.swing.JPanel {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        เงินเดือน1 = new javax.swing.JTextPane();
        เงินเดือน = new javax.swing.JLabel();
        โบนัส = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        โบนัส2 = new javax.swing.JTextPane();
        รายได้ = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        รายได้3 = new javax.swing.JTextPane();
        คำนวณ = new javax.swing.JButton();
        Sum = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Sum1 = new javax.swing.JTextPane();
        มีเงินได้ = new javax.swing.JCheckBox();
        สมรส = new javax.swing.JCheckBox();
        มีบุตร = new javax.swing.JCheckBox();
        Save = new javax.swing.JButton();
        DATA = new javax.swing.JButton();
        Name = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Name1 = new javax.swing.JTextPane();

        jScrollPane1.setViewportView(เงินเดือน1);

        เงินเดือน.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        เงินเดือน.setText("เงินเดือน(ต่อเดือน)");

        โบนัส.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        โบนัส.setText("โบนัส");

        jScrollPane2.setViewportView(โบนัส2);

        รายได้.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        รายได้.setText("รายได้อื่นๆ");
        รายได้.setToolTipText("");

        jScrollPane3.setViewportView(รายได้3);

        คำนวณ.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        คำนวณ.setText("คำนวณ");

        Sum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Sum.setText("ยอดรวมทั้งหมด");

        jScrollPane4.setViewportView(Sum1);

        มีเงินได้.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        มีเงินได้.setText("ผู้มีเงินได้");

        สมรส.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        สมรส.setText("สมรส");

        มีบุตร.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        มีบุตร.setText("มีบุตร");

        Save.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Save.setText("บันทึกข้อมูล");

        DATA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DATA.setText("Data Base");

        Name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Name.setText("ชื่อ - นามสกุล");

        jScrollPane5.setViewportView(Name1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Sum)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane4)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(เงินเดือน)
                            .addComponent(รายได้)
                            .addComponent(โบนัส)
                            .addComponent(Name))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(สมรส)
                                    .addComponent(มีเงินได้)
                                    .addComponent(มีบุตร))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Save)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DATA))
                            .addComponent(คำนวณ))))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Name)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(เงินเดือน)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(โบนัส))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(รายได้)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(มีเงินได้)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(สมรส)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(มีบุตร)
                .addGap(18, 18, 18)
                .addComponent(คำนวณ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Save)
                    .addComponent(DATA))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DATA;
    private javax.swing.JLabel Name;
    private javax.swing.JTextPane Name1;
    private javax.swing.JButton Save;
    private javax.swing.JLabel Sum;
    private javax.swing.JTextPane Sum1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton คำนวณ;
    private javax.swing.JCheckBox มีบุตร;
    private javax.swing.JCheckBox มีเงินได้;
    private javax.swing.JLabel รายได้;
    private javax.swing.JTextPane รายได้3;
    private javax.swing.JCheckBox สมรส;
    private javax.swing.JLabel เงินเดือน;
    private javax.swing.JTextPane เงินเดือน1;
    private javax.swing.JLabel โบนัส;
    private javax.swing.JTextPane โบนัส2;
    // End of variables declaration//GEN-END:variables
}
